[package]
name = "textmode"
version = "0.1.0"
authors = ["Jesse Luehrs <doy@tozt.net>"]
edition = "2018"

description = "terminal interaction library backed by a real terminal parser"
repository = "https://git.tozt.net/textmode"
readme = "README.md"
keywords = ["curses", "vt100", "terminal", "tui"]
categories = ["asynchronous", "command-line-interface"]
license = "MIT"

[dependencies]
itoa = "0.4.8"
nix = "0.23.0"
terminal_size = "0.1.17"
thiserror = "1.0.30"
vt100 = "0.12.0"

blocking = { version = "1.1.0", optional = true }
futures-lite = { version = "1.12.0", optional = true }

[features]
default = []
async = ["blocking", "futures-lite"]

[dev-dependencies]
assert_cmd = "2.0.2"
assert_fs = "1.0.6"
escargot = "0.5.6"
libc = "0.2.107"
pty-process = { version = "0.1.1", features = ["backend-smol"] }
smol = "1.2.5"
